[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
api-models = { path = "../api/api-models" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12.7", features = ["json"] }